version: '3.7'
services:
  exec-service-name:
    image: belldata/vscode-dev:golang-1.14-alpine
    volumes:
      - .:/src/:delegated
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    networks:
      - bxlink_network
    container_name: exec-service-name
networks:
  default:
    external:
      name: bridge
  bxlink_network:
    external: true
